"""Asset and rights manifests for the synthetic L0 corpus (P00-T07c, G03-L0)."""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

from .. import GENERATOR_VERSION
from ..schemas import PermittedAct, ReferenceAsset, RegionAssuranceMethod, RightsGrant, to_json
from .generator import (
    HASH_BASIS_FPS,
    Edition,
    EditionKind,
    NaturalScene,
    PrivateScreen,
    PrivateScreenKind,
    absent_works,
    content_hash,
    gallery_works,
)

L0_GRANT_ID = "GRANT-L0-SELF-SYNTH-001"


def l0_rights_grant() -> RightsGrant:
    """Self-grant for self-created synthetic material. Not a licence for any real work.

    approval_status is PENDING_REVIEW until the named rights reviewer (P00-T07) signs.
    """
    return RightsGrant(
        grant_id=L0_GRANT_ID,
        licensor="Detect A Clip project — synthetic generator (self-created)",
        chain_of_title_evidence=f"Procedurally generated by {GENERATOR_VERSION}; no third-party footage, fonts (OpenCV Hershey only) or marks.",
        permitted_acts=[
            PermittedAct.INGEST_REFERENCE,
            PermittedAct.BUILD_INDEX,
            PermittedAct.LOCAL_DISTRIBUTION,
            PermittedAct.TRANSIENT_QUERY,
            PermittedAct.DECISION,
            PermittedAct.DISPLAY_METADATA,
            PermittedAct.DERIVATIVE_DESCRIPTOR,
            PermittedAct.EVALUATION,
            # DISPLAY_STILL and TRAINING deliberately absent.
        ],
        territories=["*"],
        valid_from="2026-10-09T00:00:00Z",
        valid_until=None,
        offline_conditions="Unrestricted for synthetic development material.",
        revocation_conditions="Regenerate manifest; no external licensor.",
        approval_status="SELF_GRANT_SYNTHETIC_PENDING_REVIEW",
        region_assurance_method=RegionAssuranceMethod.NONE,
    )


def build_asset_manifest(n_works: int = 20, n_absent: int = 10, n_natural: int = 6, with_hashes: bool = True) -> Dict:
    now = datetime.now(timezone.utc).isoformat()
    assets: List[Dict] = []

    def add(asset: ReferenceAsset, family: str, extra: Dict) -> None:
        d = json.loads(to_json(asset))
        d["family"] = family
        d.update(extra)
        assets.append(d)

    for w in gallery_works(n_works):
        for kind in EditionKind:
            ed = Edition(w, kind)
            h = content_hash(ed.render_frame, ed.duration_s) if with_hashes else "UNHASHED"
            add(
                ReferenceAsset(
                    asset_id=ed.asset_id, work_id=w.work_id, series_id=None, episode_id=None,
                    edition_id=ed.edition_id, segment_ids=[], source="synthetic-generator",
                    content_hash=h, is_query_only=False, grant_id=L0_GRANT_ID, created_at=now,
                    derivative_rights=True, local_distribution_rights=True, training_rights=False,
                    display_rights=True,
                ),
                "GALLERY_WORK",
                {"seed": w.seed, "duration_s": ed.duration_s, "synthetic_title": w.synthetic_title},
            )
    for w in absent_works(n_absent):
        ed = Edition(w, EditionKind.THEATRICAL)
        h = content_hash(ed.render_frame, ed.duration_s) if with_hashes else "UNHASHED"
        add(
            ReferenceAsset(
                asset_id=ed.asset_id, work_id=w.work_id, series_id=None, episode_id=None,
                edition_id=ed.edition_id, segment_ids=[], source="synthetic-generator",
                content_hash=h, is_query_only=True, grant_id=L0_GRANT_ID, created_at=now,
                derivative_rights=True, local_distribution_rights=False, training_rights=False,
                display_rights=False,
            ),
            "ABSENT_WORK",
            {"seed": w.seed, "duration_s": ed.duration_s},
        )
    for i in range(n_natural):
        ns = NaturalScene(i, 7000 + i)
        h = content_hash(ns.render_frame, ns.duration_s) if with_hashes else "UNHASHED"
        add(
            ReferenceAsset(
                asset_id=ns.asset_id, work_id="NONE", series_id=None, episode_id=None, edition_id="NONE",
                segment_ids=[], source="synthetic-generator", content_hash=h, is_query_only=True,
                grant_id=L0_GRANT_ID, created_at=now, derivative_rights=True, local_distribution_rights=False,
                training_rights=False, display_rights=False,
            ),
            "NATURAL_UNMARKED",
            {"seed": ns.seed, "duration_s": ns.duration_s},
        )
    for kind in PrivateScreenKind:
        ps = PrivateScreen(kind, 1)
        f = ps.render_frame(0.0)
        h = hashlib.sha256(f.tobytes()).hexdigest() if with_hashes else "UNHASHED"
        add(
            ReferenceAsset(
                asset_id=ps.asset_id, work_id="NONE", series_id=None, episode_id=None, edition_id="NONE",
                segment_ids=[], source="synthetic-generator", content_hash=h, is_query_only=True,
                grant_id=L0_GRANT_ID, created_at=now, derivative_rights=False, local_distribution_rights=False,
                training_rights=False, display_rights=False,
            ),
            "SYNTHETIC_PRIVATE_SCREEN",
            {"seed": 1, "overlay_class": kind.value, "note": "fictional seeded text only; no real private pixels"},
        )

    manifest = {
        "manifest_type": "L0_ASSET_MANIFEST",
        "generator_version": GENERATOR_VERSION,
        "content_hash_basis": f"SHA-256 over BGR uint8 640x360 frames sampled at {HASH_BASIS_FPS} fps",
        "created_at": now,
        "counts": {
            "gallery_works": n_works,
            "editions_per_work": len(EditionKind),
            "absent_works": n_absent,
            "natural_unmarked": n_natural,
            "synthetic_private_screens": len(PrivateScreenKind),
            "total_assets": len(assets),
        },
        "quality_claim": "NONE — synthetic diagnostic material; not industry-quality footage; not six-industry coverage.",
        "grant": json.loads(to_json(l0_rights_grant())),
        "assets": assets,
    }
    body = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode()
    manifest["manifest_sha256"] = hashlib.sha256(body).hexdigest()
    return manifest


def write_manifests(out_dir: Path, **kwargs) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    m = build_asset_manifest(**kwargs)
    p = out_dir / "ASSET_MANIFEST.json"
    p.write_text(json.dumps(m, indent=1, sort_keys=True), encoding="utf-8")
    (out_dir / "RIGHTS_MANIFEST.json").write_text(
        json.dumps(json.loads(to_json(l0_rights_grant())), indent=1, sort_keys=True), encoding="utf-8"
    )
    return p
