"""Asset and rights manifests for the synthetic L0 corpus (P00-T07c, G03-L0)."""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

from .. import GENERATOR_VERSION
from ..schemas import PermittedAct, ReferenceAsset, RegionAssuranceMethod, RightsGrant, to_json
from .generator import (
    HASH_BASIS_FPS,
    Edition,
    EditionKind,
    NaturalScene,
    PrivateScreen,
    PrivateScreenKind,
    absent_works,
    content_hash,
    gallery_works,
)

L0_GRANT_ID = "GRANT-L0-SELF-SYNTH-001"


def l0_rights_grant() -> RightsGrant:
    """Self-grant for self-created synthetic material. Not a licence for any real work.

    approval_status is PENDING_REVIEW until the named rights reviewer (P00-T07) signs.
    """
    return RightsGrant(
        grant_id=L0_GRANT_ID,
        licensor="Detect A Clip project — synthetic generator (self-created)",
        chain_of_title_evidence=f"Procedurally generated by {GENERATOR_VERSION}; no third-party footage, fonts (OpenCV Hershey only) or marks.",
        permitted_acts=[
            PermittedAct.INGEST_REFERENCE,
            PermittedAct.BUILD_INDEX,
            PermittedAct.LOCAL_DISTRIBUTION,
            PermittedAct.TRANSIENT_QUERY,
            PermittedAct.DECISION,
            PermittedAct.DISPLAY_METADATA,
            PermittedAct.DERIVATIVE_DESCRIPTOR,
            PermittedAct.EVALUATION,
            # DISPLAY_STILL and TRAINING deliberately absent.
        ],
        territories=["*"],
        valid_from="2026-10-09T00:00:00Z",
        valid_until=None,
        offline_conditions="Unrestricted for synthetic development material.",
        revocation_conditions="Regenerate manifest; no external licensor.",
        approval_status="SELF_GRANT_SYNTHETIC_PENDING_REVIEW",
        region_assurance_method=RegionAssuranceMethod.NONE,
    )


def build_asset_manifest(with_hashes: bool = True) -> Dict:
    """Asset manifest for every fixtures-v3.x family (gallery editions, absent works, natural
    scenes, synthetic private screens). Content hashes make provenance reproducible; the
    manifest hash excludes the creation timestamp so it is stable across rebuilds."""
    from .fixtures import FAMILIES, FIXTURE_VERSION, build_family

    now = datetime.now(timezone.utc).isoformat()
    assets: List[Dict] = []

    def add(asset: ReferenceAsset, family: str, extra: Dict) -> None:
        d = json.loads(to_json(asset))
        d.pop("created_at", None)
        d["family"] = family
        d.update(extra)
        assets.append(d)

    counts: Dict[str, int] = {}
    for fam in FAMILIES:
        F = build_family(fam)
        for ed in F.gallery_editions():
            w = ed.work
            h = content_hash(ed.render_frame, ed.duration_s) if with_hashes else "UNHASHED"
            kind = "EPISODE" if getattr(w, "series_id", None) else ("STOCK_SHARING_WORK" if w in F.stock_pair else "GALLERY_WORK")
            add(ReferenceAsset(asset_id=ed.asset_id, work_id=w.work_id, series_id=getattr(w, "series_id", None),
                               episode_id=getattr(w, "episode_id", None), edition_id=ed.edition_id, segment_ids=[],
                               source="synthetic-generator", content_hash=h, is_query_only=False, grant_id=L0_GRANT_ID,
                               created_at=now, derivative_rights=True, local_distribution_rights=True,
                               training_rights=False, display_rights=True),
                f"{fam}:{kind}", {"seed": w.seed, "duration_s": ed.duration_s})
        for w in F.absent:
            ed = Edition(w, EditionKind.THEATRICAL)
            h = content_hash(ed.render_frame, ed.duration_s) if with_hashes else "UNHASHED"
            add(ReferenceAsset(asset_id=ed.asset_id, work_id=w.work_id, series_id=None, episode_id=None,
                               edition_id=ed.edition_id, segment_ids=[], source="synthetic-generator", content_hash=h,
                               is_query_only=True, grant_id=L0_GRANT_ID, created_at=now, derivative_rights=True,
                               local_distribution_rights=False, training_rights=False, display_rights=False),
                f"{fam}:ABSENT_WORK", {"seed": w.seed, "duration_s": ed.duration_s})
        for ns in F.natural:
            h = content_hash(ns.render_frame, ns.duration_s) if with_hashes else "UNHASHED"
            add(ReferenceAsset(asset_id=f"{fam}-{ns.asset_id}", work_id="NONE", series_id=None, episode_id=None,
                               edition_id="NONE", segment_ids=[], source="synthetic-generator", content_hash=h,
                               is_query_only=True, grant_id=L0_GRANT_ID, created_at=now, derivative_rights=True,
                               local_distribution_rights=False, training_rights=False, display_rights=False),
                f"{fam}:NATURAL_UNMARKED", {"seed": ns.seed, "duration_s": ns.duration_s})
        counts[fam] = sum(1 for a in assets if a["family"].startswith(fam + ":"))
    for kind in PrivateScreenKind:
        for seed in (1, 2):
            ps = PrivateScreen(kind, seed)
            h = hashlib.sha256(ps.render_frame(0.0).tobytes()).hexdigest() if with_hashes else "UNHASHED"
            add(ReferenceAsset(asset_id=ps.asset_id, work_id="NONE", series_id=None, episode_id=None, edition_id="NONE",
                               segment_ids=[], source="synthetic-generator", content_hash=h, is_query_only=True,
                               grant_id=L0_GRANT_ID, created_at=now, derivative_rights=False,
                               local_distribution_rights=False, training_rights=False, display_rights=False),
                "SYNTHETIC_PRIVATE_SCREEN", {"seed": seed, "overlay_class": kind.value,
                                             "note": "fictional seeded text only; no real private pixels"})

    manifest = {
        "manifest_type": "L0_ASSET_MANIFEST",
        "generator_version": GENERATOR_VERSION,
        "fixture_version": FIXTURE_VERSION,
        "content_hash_basis": f"SHA-256 over BGR uint8 640x360 frames sampled at {HASH_BASIS_FPS} fps (queries add the capture channel at evaluation time and are not hashed here)",
        "counts": {**{f"{k}_assets": v for k, v in counts.items()}, "total_assets": len(assets)},
        "quality_claim": "NONE: synthetic diagnostic material; not industry-quality footage; not six-industry coverage.",
        "grant": json.loads(to_json(l0_rights_grant())),
        "assets": assets,
    }
    body = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode()
    manifest["manifest_sha256"] = hashlib.sha256(body).hexdigest()
    manifest["created_at"] = now
    return manifest


def write_manifests(out_dir: Path, **kwargs) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    m = build_asset_manifest(**kwargs)
    p = out_dir / "ASSET_MANIFEST.json"
    p.write_text(json.dumps(m, indent=1, sort_keys=True), encoding="utf-8")
    (out_dir / "RIGHTS_MANIFEST.json").write_text(
        json.dumps(json.loads(to_json(l0_rights_grant())), indent=1, sort_keys=True), encoding="utf-8"
    )
    return p
