"""DAC-DHASH-v1: a platform-exact 64-bit difference hash (P04-T08 preparation).

The LAB descriptor HASH64 uses OpenCV Gaussian blur and INTER_AREA resizing, which a Kotlin
or Swift engine cannot reproduce bit for bit. DAC-DHASH-v1 is defined with integer arithmetic
only, so Python, Kotlin and Swift produce identical bits (checked by golden vectors):

 1. Luma per pixel: Y = (77·R + 150·G + 29·B + 128) >> 8           (integer BT.601 approx.)
 2. 9×8 area means: column cell i spans x ∈ [⌊i·W/9⌋, ⌊(i+1)·W/9⌋), row cell j spans
    y ∈ [⌊j·H/8⌋, ⌊(j+1)·H/8⌋); mean = ⌊sum / count⌋.
 3. For each row j and column i in 0..7: bit = mean[j][i+1] > mean[j][i]; bits are taken
    row-major, most significant bit first, giving one unsigned 64-bit value.

Status: CANDIDATE. Not used by the LAB pipeline; adopting it for packs is a method change
that needs new calibration and a new sealed evaluation family.
"""
from __future__ import annotations

import numpy as np

SPEC = "DAC-DHASH-v1"


def luma_u8(rgb: np.ndarray) -> np.ndarray:
    """rgb: HxWx3 uint8 in R,G,B order."""
    r = rgb[:, :, 0].astype(np.int32)
    g = rgb[:, :, 1].astype(np.int32)
    b = rgb[:, :, 2].astype(np.int32)
    return ((77 * r + 150 * g + 29 * b + 128) >> 8).astype(np.int32)


def dac_dhash_v1(rgb: np.ndarray) -> int:
    h, w = rgb.shape[:2]
    if w < 9 or h < 8:
        raise ValueError("frame too small")
    y = luma_u8(rgb)
    means = np.zeros((8, 9), dtype=np.int64)
    for j in range(8):
        y0, y1 = (j * h) // 8, ((j + 1) * h) // 8
        for i in range(9):
            x0, x1 = (i * w) // 9, ((i + 1) * w) // 9
            cell = y[y0:y1, x0:x1]
            means[j, i] = int(cell.sum()) // cell.size
    v = 0
    for j in range(8):
        for i in range(8):
            v = (v << 1) | int(means[j, i + 1] > means[j, i])
    return v


class XorShift32:
    """Deterministic test-frame source shared with the Kotlin/Swift golden tests."""

    def __init__(self, seed: int):
        self.s = (seed & 0xFFFFFFFF) or 0x9E3779B9

    def next(self) -> int:
        s = self.s
        s ^= (s << 13) & 0xFFFFFFFF
        s ^= s >> 17
        s ^= (s << 5) & 0xFFFFFFFF
        self.s = s & 0xFFFFFFFF
        return self.s


def test_frame(seed: int, w: int, h: int) -> np.ndarray:
    """Smooth gradient + a seeded rectangle + low-amplitude noise, consumed in y→x→channel order."""
    rng = XorShift32(seed)
    rx, ry = rng.next() % w, rng.next() % h
    rw, rh = 1 + rng.next() % (w // 2), 1 + rng.next() % (h // 2)
    col = (rng.next() & 255, rng.next() & 255, rng.next() & 255)
    out = np.zeros((h, w, 3), dtype=np.uint8)
    for yy in range(h):
        for xx in range(w):
            inside = rx <= xx < rx + rw and ry <= yy < ry + rh
            for ch in range(3):
                base = col[ch] if inside else ((xx * 255) // max(1, w - 1) + (yy * 255) // max(1, h - 1) * (ch + 1)) & 255
                noise = (rng.next() >> 28) - 8  # −8..7
                out[yy, xx, ch] = max(0, min(255, base + noise))
    return out


GOLDEN_SIZES = [(9, 8), (16, 9), (64, 36), (97, 53), (160, 90), (320, 180)]


def write_golden(path, seeds=range(1, 8)) -> None:
    lines = [f"# {SPEC} golden vectors: X <seed> <width> <height> <hash hex>; generated by l0/dac_l0/index/exact.py"]
    for seed in seeds:
        for (w, h) in GOLDEN_SIZES:
            lines.append(f"X {seed} {w} {h} {dac_dhash_v1(test_frame(seed, w, h)):016x}")
    from pathlib import Path

    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    import sys

    write_golden(sys.argv[1])
    print("wrote", sys.argv[1])


def content_frame(seed: int, w: int, h: int, bx: int = 16, by: int = 9) -> np.ndarray:
    """Discriminative test content: a bx×by grid of seeded random colour blocks (block size
    w//bx × h//by, remainder filled by the last block) plus ±8 noise. Consumption order:
    block colours row-major (3 draws each), then per-pixel noise y→x→channel."""
    rng = XorShift32(seed)
    cols = [[(rng.next() & 255, rng.next() & 255, rng.next() & 255) for _ in range(bx)] for _ in range(by)]
    out = np.zeros((h, w, 3), dtype=np.uint8)
    bw, bh = max(1, w // bx), max(1, h // by)
    for yy in range(h):
        cy = min(by - 1, yy // bh)
        for xx in range(w):
            cx = min(bx - 1, xx // bw)
            for ch in range(3):
                v = cols[cy][cx][ch] + (rng.next() >> 28) - 8
                out[yy, xx, ch] = max(0, min(255, v))
    return out
