// Shared helpers for the golden-file tests. Golden files live with the Android unit tests and
// are generated by the Python reference (l0/dac_l0/eval/*); paths resolve from this source file.
import Foundation
@testable import DetectAClipCore

enum Golden {
    static func url(_ name: String) -> URL {
        URL(fileURLWithPath: #filePath).deletingLastPathComponent()
            .appendingPathComponent("../../../android/app/src/test/resources/\(name)").standardized
    }

    static func lines(_ name: String) throws -> [String] {
        try String(contentsOf: url(name), encoding: .utf8)
            .split(separator: "\n", omittingEmptySubsequences: true)
            .map { String($0).trimmingCharacters(in: CharacterSet(charactersIn: "\r")) }
    }

    static func hex(_ s: Substring) -> [UInt8] { hex(String(s)) }

    static func hex(_ s: String) -> [UInt8] {
        let u = Array(s.utf8)
        func v(_ c: UInt8) -> UInt8 { c <= 57 ? c - 48 : (c | 0x20) - 87 }
        return stride(from: 0, to: u.count - 1, by: 2).map { v(u[$0]) << 4 | v(u[$0 + 1]) }
    }

    static func thresholds(_ t: [String]) -> Recognition.Thresholds {
        var th = Recognition.Thresholds()
        th.minQualifiedFrames = Int(t[1])!; th.verifiedMinSupport = Int(t[2])!; th.verifiedMinSupportFraction = Double(t[3])!
        th.verifiedMinSpanMs = Int(t[4])!; th.verifiedMaxMeanDistFrac = Double(t[5])!; th.verifiedMinMargin = Int(t[6])!
        th.possibleMinSupport = Int(t[7])!; th.possibleMinSpanMs = Int(t[8])!; th.possibleMaxMeanDistFrac = Double(t[9])!
        th.possibleOnCompetition = t[10] == "1"; th.episodeMargin = Int(t[11])!; th.radius = Double(t[12])!
        return th
    }

    /// The synthetic pack embedded in golden_pipeline.txt.
    static func pipelinePack() throws -> PackIndex {
        let line = try lines("golden_pipeline.txt").first { $0.hasPrefix("PACKHEX ") }!
        return try PackIndex.parse(hex(line.dropFirst(8)))
    }
}

/// Same frame composition as l0/dac_l0/eval/pipeline_golden.compose (RGB, 3 bytes per pixel).
enum Compose {
    static func scaleNearest(_ src: [UInt8], _ w: Int, _ h: Int, _ nw: Int, _ nh: Int) -> [UInt8] {
        var out = [UInt8](repeating: 0, count: nw * nh * 3)
        for y in 0..<nh { for x in 0..<nw {
            let sy = (y * h) / nh, sx = (x * w) / nw
            for c in 0..<3 { out[(y * nw + x) * 3 + c] = src[(sy * w + sx) * 3 + c] }
        } }
        return out
    }

    static func place(_ dst: inout [UInt8], _ w: Int, _ src: [UInt8], _ sw: Int, _ sh: Int, _ ox: Int, _ oy: Int) {
        for y in 0..<sh { for k in 0..<(sw * 3) { dst[((oy + y) * w + ox) * 3 + k] = src[y * sw * 3 + k] } }
    }

    static func frame(seed: UInt32, variant: String, bright: Int, w: Int, h: Int) -> [UInt8] {
        if variant == "black" { return [UInt8](repeating: 0, count: w * h * 3) }
        let c = DacDhash.contentFrame(seed: seed, w: w, h: h)
        var out: [UInt8]
        switch variant {
        case "full": out = c
        case "mirror":
            out = c
            for y in 0..<h { for x in 0..<w { for k in 0..<3 { out[(y * w + x) * 3 + k] = c[(y * w + (w - 1 - x)) * 3 + k] } } }
        case "letterbox":
            out = [UInt8](repeating: 0, count: w * h * 3); place(&out, w, scaleNearest(c, w, h, w, 26), w, 26, 0, 5)
        case "pillarbox":
            out = [UInt8](repeating: 0, count: w * h * 3); place(&out, w, scaleNearest(c, w, h, 48, h), 48, h, 8, 0)
        case "pip":
            out = [UInt8](repeating: 235, count: w * h * 3)
            for i in 0..<(5 * w * 3) { out[i] = 60 }
            place(&out, w, scaleNearest(c, w, h, 40, 22), 40, 22, 12, 9)
        default: fatalError(variant)
        }
        if bright != 0 { out = out.map { DacDhash.clampByte(Int($0) + bright) } }
        return out
    }

    /// RGB -> padded RGBA plane (rowStride > width * 4) with garbage in the padding.
    static func paddedRGBA(_ rgb: [UInt8], _ w: Int, _ h: Int, pad: Int) -> (bytes: [UInt8], rowStride: Int) {
        let rs = w * 4 + pad
        var b = [UInt8](repeating: 0x5A, count: rs * h)
        for y in 0..<h { for x in 0..<w {
            let p = y * rs + x * 4
            b[p] = rgb[(y * w + x) * 3]; b[p + 1] = rgb[(y * w + x) * 3 + 1]; b[p + 2] = rgb[(y * w + x) * 3 + 2]; b[p + 3] = 255
        } }
        return (b, rs)
    }

    static func luma(_ plane: (bytes: [UInt8], rowStride: Int), _ w: Int, _ h: Int) throws -> [Int] {
        try plane.bytes.withUnsafeBytes { try FrameView(base: $0, width: w, height: h, rowStride: plane.rowStride, pixelStride: 4).toLuma() }
    }
}

/// "R <state> <work> <edition> <episode> <flags> <segments>" exactly as the Python generators
/// write it. Built in explicit steps to keep the type checker fast.
enum DecisionLine {
    static func opt(_ s: String?) -> String { s ?? "-" }

    static func segment(_ g: Recognition.Segment) -> String {
        let off: String = g.referenceOffsetMs.map { String($0) } ?? "-"
        let parts: [String] = [g.workId, opt(g.editionId), String(g.queryStartMs), String(g.queryEndMs), off, String(g.supportingFrames)]
        return parts.joined(separator: "@")
    }

    static func format(_ d: Recognition.Decision) -> String {
        let segs: String = d.segments.isEmpty ? "-" : d.segments.map(segment).joined(separator: "|")
        let flags: String = d.flags.isEmpty ? "-" : d.flags.joined(separator: ",")
        let parts: [String] = ["R", d.state.rawValue, opt(d.workId), opt(d.editionId), opt(d.episodeId), flags, segs]
        return parts.joined(separator: " ")
    }
}
